LostAndFound/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from .views import Index

app_name = "LostAndFound"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('items/', include('items.urls')),
    path('site_admin/', include('site_admin.urls')),
    path('user/', include('common_user.urls')),
    path('', include('authentication.urls')),
    path('', Index.as_view(), name="index"),
    # path('home/', TemplateView.as_view(template_name="home.html"), name="home"),
    path('info/', TemplateView.as_view(template_name="info.html"), name="info"),
]

items/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views
from .views import Index  # Ensure you're importing the Index view

app_name = 'items'
urlpatterns = [
    path('report/lost/', views.ReportItemView.as_view(is_found=False), name='report_lost'),
    path('report/found/', views.ReportItemView.as_view(is_found=True), name='report_found'),
    path('report/success/', TemplateView.as_view(template_name='items/report_success.html'), name='report_success'),
    path("<int:id>/", views.Detail.as_view(), name='details'),
    path('<int:id>/delete', views.delete, name='delete'),
    path('<int:id>/flag', views.flag, name='flag'),
    path('lost/', views.Index.as_view(is_found=False), name='index_lost'),
    path('found/', views.Index.as_view(is_found=True), name='index_found'),
    path('locations', views.getLocations, name='locations'),
]

site_admin/urls.py
from django.urls import path

from items.models import Status
from . import views

app_name = 'site_admin'
urlpatterns = [
    path("", views.review_redirect),
    path("review/", views.ReviewItems.as_view(), name="review"),
    path("review/<int:id>/", views.Detail.as_view(), name="detail"),
    path("review/<int:id>/reject/", views.Resolve.as_view(status=Status.REJECTED), name="remove"),
    path("review/<int:id>/resolve/", views.Resolve.as_view(status=Status.RESOLVED), name="resolve"),
    path("review/<int:id>/update/", views.update, name="update"),
]

items/models.py
from django.conf import settings
from django.core.validators import RegexValidator
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext as translate
from django.core.exceptions import ValidationError
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.core.files.storage import default_storage


class Location_Category(models.Model):
    name = models.CharField(max_length=200)

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Location(models.Model):
    name = models.CharField(max_length=200)
    category = models.ForeignKey(Location_Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Tag(models.IntegerChoices):
    OTHER = 1

    # TECHNOLOGY
    AIR_PODS = 100
    PHONE = 101
    COMPUTER = 102
    IPAD = 103
    HEADPHONES = 104
    CAMERA = 105
    TABLET = 106
    SMART_WATCH = 107
    CHARGER = 108

    # CLOTHING & WEATHER
    RAIN_JACKET = 300
    UMBRELLA = 301
    SUNGLASSES = 302
    COAT = 303
    HAT = 304
    GLOVES = 306
    SCARF = 307
    SHOES = 308

    # ACCESSORIES
    CREDIT_CARD = 400
    KEYS = 401
    WATCH = 402
    BACKPACK = 403
    PURSE = 404
    JEWELRY = 405
    WALLET = 406
    PASSPORT = 407
    ID = 408
    GLASSES = 409
    WATER_BOTTLE = 410
    BOOK = 411
    NOTEBOOK = 412
    PENCIL_CASE = 413
    SPORTS_EQUIPMENT = 414

    # TRANSPORTATION
    BICYCLE = 500
    SCOOTER = 501
    HELMET = 502


class Status(models.IntegerChoices):
    NEW = 100, "Submitted"  # automatically assigned whenever a report is created

    FLAGGED = 200, "Flagged"  # manually selected by a common user

    IN_PROGRESS = 300, "Under Review"  # automatically assigned whenever a site admin clicks on an item's detail report

    RESOLVED = 400, "Approved"  # manually selected by a site admin

    REJECTED = 500, "Rejected" # Manually selected by a site admin


def return_expiration_date():
    return (timezone.now() + timezone.timedelta(days=30)).date()


def date_validator(value):
    if timezone.now().date() < value:
        raise ValidationError(translate("The date an item was lost/found must not be in the future."))


class PhoneNumberValidator(RegexValidator):
    regex = r"(\+\d+ ?)?((\(\d{3}\))|(\d{3}))(-| )?(\d{3})(-| )?(\d{4})"
    message = "Phone number must include ten numeric digits, separated using spaces, dashes, or parentheses. Area code is optional."


class Item(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, default=None,
                             on_delete=models.SET_DEFAULT)

    item_name = models.CharField(max_length=50)
    description = models.TextField(max_length=500)

    location_category = models.ForeignKey(Location_Category, on_delete=models.CASCADE)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    status = models.PositiveIntegerField(choices=Status, default=100)
    tag = models.PositiveIntegerField(choices=Tag)

    date = models.DateField(validators=[date_validator], default=timezone.now)

    expiration_date = models.DateField(default=return_expiration_date)

    email = models.EmailField(blank=True, default=None, null=True)
    phone_number = models.CharField(max_length=50, blank=True, null=True, default=None,
                                    validators=[PhoneNumberValidator()])

    resolve_text = models.CharField(max_length=1024, blank=True, default=None, null=True)
    is_found = models.BooleanField(default=False)

    def __str__(self):
        return self.item_name


class ItemFile(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    file = models.FileField(upload_to='imageUpload/')
    type = models.CharField(max_length=30)


@receiver(post_delete, sender=ItemFile)
def delete_file_from_s3(sender, instance, **kwargs):
    if instance.file:
        file_path = instance.file.name
        if default_storage.exists(file_path):
            default_storage.delete(file_path)

site_admin/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden, JsonResponse
from django.urls import reverse
from django.views import generic
import json

from items.models import Item, Status, ItemFile, Location, Location_Category


class ReviewItems(LoginRequiredMixin, generic.ListView):
    template_name = "site_admin/review.html"
    context_object_name = "items"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and not request.user.is_site_admin:
            return HttpResponseForbidden("You are not allowed to access this page.")

        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        items = Item.objects.filter(status__in=[Status.NEW, Status.FLAGGED, Status.IN_PROGRESS])

        # Order items by date
        items = items.order_by('-date')
        
        for item in items:
            item.files = list(ItemFile.objects.filter(item=item.id))

        return items


class Detail(LoginRequiredMixin, generic.DetailView):
    model = Item
    template_name = "site_admin/detail.html"
    context_object_name = "item"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and not request.user.is_site_admin:
            return HttpResponseForbidden("You are not allowed to access this page.")

        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        item = Item.objects.get(id=self.kwargs['id'])
        item.files = list(ItemFile.objects.filter(item=item.id))

        if item.status in [Status.NEW, Status.FLAGGED]:
            item.status = Status.IN_PROGRESS
            item.save(update_fields=['status'])

        return item

    def get_context_data(self, **kwargs):
        context = super(Detail, self).get_context_data(**kwargs)
        context['location_name'] = self.get_location_name(context['item'].location_id)
        return context

    def get_location_name(self, location_id):
        location = get_object_or_404(Location, pk=location_id)
        return location.name


class Resolve(LoginRequiredMixin, generic.DetailView):
    model = Item
    template_name = "site_admin/resolution_notes.html"
    context_object_name = "item"
    status = None

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and not request.user.is_site_admin:
            return HttpResponseForbidden("You are not allowed to access this page.")

        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        item = Item.objects.get(id=self.kwargs['id'], status__in=[Status.NEW, Status.FLAGGED, Status.IN_PROGRESS])

        return item

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['status'] = self.status
        context['status_resolved'] = self.status == Status.RESOLVED
        context['status_rejected'] = self.status == Status.REJECTED
        return context


def update(request, id):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(settings.LOGIN_URL)
    if not request.user.is_site_admin:
        return HttpResponseForbidden("You are not allowed to access this page.")

    item = get_object_or_404(Item, pk=id, status__in=[Status.NEW, Status.FLAGGED, Status.IN_PROGRESS])

    if request.method == "POST":
        status = request.POST.get('status')
        if not status:
            status = Status.RESOLVED
        item.status = status
        item.resolve_text = request.POST.get("resolve_text", "")
        item.save()
        messages.success(request, "Successfully resolved item.")

        return HttpResponseRedirect(reverse('site_admin:review'))

    else:
        return HttpResponse(reverse('site_admin:detail', args=(id,)))


def review_redirect(request):
    return HttpResponseRedirect(reverse('site_admin:review'))


def getLocations(request):
    data = json.loads(request.body)

    location_categoryID = data["id"]

    possibleLocations = Location.objects.filter(category__id=location_categoryID)

    print(location_categoryID)

    return JsonResponse(list(possibleLocations.values("id", "name")), safe=False)

templates/site_admin/detail.html
<!DOCTYPE html>

{% extends "base.html" %}
{% load static %}

{% block content %}
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/item-detail.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{#        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">#}
    </head>

    <body>
    {% if user.is_site_admin %}
        <div class="content">
            <div class="detail-content-container">
                <div class="detail-info">
                    <div class="info-top-container">
                        <div class="header-container">
                            <div>
                                <h3> {{ item }} </h3>
                            </div>
                        </div>

                        {% if item.tag %}
                            <div class="tag-container">
                                <i class="fa fa-tag"></i>
                                <p class="tag-text"> {{ item.get_tag_display }} </p>
                            </div>
                        {% endif %}

                        {% if item.location %}
                            <div class="specific-info-container" id="location-container">
                                <h4> Location: </h4>
                                <p> {{ location_name }} </p>
                            </div>
                        {% endif %}

                        {% if item.date %}
                            <div class="specific-info-container">
                                <h4>
                                Date 
                                {% if item.is_found %} Found: 
                                {% else %} Lost: {% endif %} 
                                </h4>
                                <p> {{ item.date }} </p>
                            </div>
                        {% endif %}

                        <div class="specific-info-container">
                            <h4> Contact information: </h4>
                            <p> 
                                {% if not item.email and not item.phone_number %}
                                    No contact information was provided.
                                {% endif %}
                                {% if item.email %}
                                    Email: {{ item.email }} <br>
                                {% endif %}
                                {% if item.phone_number %}
                                    Phone: {{ item.phone_number }}
                                {% endif %}
                            </p>
                        </div>

                        <div class="specific-info-container" id="description-container">
                            <h4>Description/Comments:</h4>
                            <div class="description-content">
                                {% if item.description %}
                                    <p>{{ item.description }}</p>
                                {% else %}
                                    <p>No comment was left</p>
                                {% endif %}
                            </div>
                        </div>  
                    </div>

                    <hr/>

                    <div class="info-bottom-container">
                        <div class="status-container">
                            <div class="status-info">
                                <h4>Post status:</h4>
                                <p>{{ item.get_status_display }}</p>
                            </div>
                            {% if item.get_status_display == "Approved" or item.get_status_display == "Rejected" %}
                                <div>
                                    {% include 'items/resolution_modal.html' %}
                                    <button id="resolutionMessageBtn" type="submit" class="btn btn-sm"
                                            data-bs-toggle="modal" data-bs-target="#resolutionModal">
                                        View Resolution Message
                                    </button>
                                </div>
                            {% endif %}
                        </div>
                        
                        <div class="post-actions">
                            <div class="resolve-post-button-container">
                                <a href="{% url "site_admin:resolve" item.id %}">
                                    <button class="btn btn-black btn-sm">
                                        Mark as approved
                                        <i class="fa fa-check"></i>
                                    </button>
    
                                </a>
                            </div>
                            <div class="remove-post-button-container">
                                <a href="{% url "site_admin:remove" item.id %}">
                                    <button id="deleteBtn" type="submit" class="btn btn-danger btn-sm"
                                        data-bs-toggle="modal" data-bs-target="#deletePostModal">
                                        <i class="fa fa-exclamation-circle"></i> Reject Post
                                    </button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                {% if item.files %}
                    <div class="files-container">
                        {% include 'items/carousel.html' %}
                    </div>
                {% endif %}
            </div>
        </div>
        </div>
    {% else %}
        <p> You do not have access to this page. </p>
    {% endif %}
    </body>
{% endblock %}

templates/site_admin/resolution_notes.html
<!-- In your templates/site_admin/resolution_notes.html -->

{% extends "base.html" %}
{% load static %}

{% block content %}
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}">
    </head>
    <body>
    <form action="{% url "site_admin:update" item.id %}" method="post">{% csrf_token %}
        <div style="text-align: center; margin-top: 15px">
            <h1>
                {% if status_resolved %} 
                    Resolve a Report
                {% elif status_rejected %}
                    Reject a Report
                {% endif %}
            </h1>
            <p>
                Item to be 
                {% if status_resolved %} 
                    resolved:
                {% elif status_rejected %}
                    rejected:
                {% endif %} <b>{{ item }}</b> <br>
                If you do not wish to add notes to this report, leave the text field blank and press submit.
            </p>
        </div>
        <div class="form-container">
            <input name="status" type="hidden" value="{{ status }}">
            <textarea name="resolve_text" class="input-basic tall" maxlength="500"></textarea>
        </div>
        
        <div style="padding-top: 20px; text-align: center">
            <input type="submit" class="btn btn-black" value="Submit">
            <a href="#" onclick="window.history.back(); return false;">
                <button class="btn btn-white">Cancel</button>
            </a>
        </div>
    </form>
    </body>
{% endblock %}

templates/site_admin/review.html
<!DOCTYPE html>
<html lang="en">

{% extends "base.html" %}
{% load static %}

{% block content %}
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" type="text/css" href="{% static 'css/item-detail.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>

    <div style="margin:auto; padding-top:2%">
        <h1>
            Review Reports
        </h1>
    </div>

    <div class="container p-3">
        {% if items %}
            {% for item in items %}
                <div class="item-container" id="{{ item.id }}">
                    <div class="item-header">
                        <div class="item-name">
                            <h3 onclick="redirectToDetail('{{ item.id }}')">{{ item.item_name }}</h3>
                        </div>

                        {% if item.tag %}
                            <div class="tag-container">
                                <i class="fa fa-tag"></i>
                                <div class="tag-text">
                                    {{ item.get_tag_display }}
                                </div>
                            </div>
                        {% endif %}
                    </div>

                    {% if item.files %}
                        <div class="files-container">
                            {% include 'items/carousel.html' %}
                        </div>
                    {% endif %}
                    <div class="item-details">
                        <div class="item-location">Location: {{ item.location }}</div>
                        <div class="item-date">
                            Date
                            {% if item.is_found %} Found:
                            {% else %} Lost: {% endif %}
                            {{ item.date }}
                        </div>
                    </div>
                    <a href="{% url 'site_admin:detail' item.id %}" class="details-link">Click to view more
                        details</a>
                </div>
            {% endfor %}


        {% else %}
            {% block empty_message %}
                <p> No items lost! </p>
            {% endblock %}
        {% endif %}
    </div>
    <script>
        function redirectToDetail(itemId) {
            window.location.href = "{% url 'site_admin:detail' 0 %}".replace("0", itemId);
        }
    </script>
    </html>
{% endblock %}