LostAndFound/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from .views import Index

app_name = "LostAndFound"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('items/', include('items.urls')),
    path('site_admin/', include('site_admin.urls')),
    path('user/', include('common_user.urls')),
    path('', include('authentication.urls')),
    path('', Index.as_view(), name="index"),
    # path('home/', TemplateView.as_view(template_name="home.html"), name="home"),
    path('info/', TemplateView.as_view(template_name="info.html"), name="info"),
]

items/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views
from .views import Index  # Ensure you're importing the Index view

app_name = 'items'
urlpatterns = [
    path('report/lost/', views.ReportItemView.as_view(is_found=False), name='report_lost'),
    path('report/found/', views.ReportItemView.as_view(is_found=True), name='report_found'),
    path('report/success/', TemplateView.as_view(template_name='items/report_success.html'), name='report_success'),
    path("<int:id>/", views.Detail.as_view(), name='details'),
    path('<int:id>/delete', views.delete, name='delete'),
    path('<int:id>/flag', views.flag, name='flag'),
    path('lost/', views.Index.as_view(is_found=False), name='index_lost'),
    path('found/', views.Index.as_view(is_found=True), name='index_found'),
    path('locations', views.getLocations, name='locations'),
]

items/models.py
from django.conf import settings
from django.core.validators import RegexValidator
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext as translate
from django.core.exceptions import ValidationError
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.core.files.storage import default_storage


class Location_Category(models.Model):
    name = models.CharField(max_length=200)

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Location(models.Model):
    name = models.CharField(max_length=200)
    category = models.ForeignKey(Location_Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Tag(models.IntegerChoices):
    OTHER = 1

    # TECHNOLOGY
    AIR_PODS = 100
    PHONE = 101
    COMPUTER = 102
    IPAD = 103
    HEADPHONES = 104
    CAMERA = 105
    TABLET = 106
    SMART_WATCH = 107
    CHARGER = 108

    # CLOTHING & WEATHER
    RAIN_JACKET = 300
    UMBRELLA = 301
    SUNGLASSES = 302
    COAT = 303
    HAT = 304
    GLOVES = 306
    SCARF = 307
    SHOES = 308

    # ACCESSORIES
    CREDIT_CARD = 400
    KEYS = 401
    WATCH = 402
    BACKPACK = 403
    PURSE = 404
    JEWELRY = 405
    WALLET = 406
    PASSPORT = 407
    ID = 408
    GLASSES = 409
    WATER_BOTTLE = 410
    BOOK = 411
    NOTEBOOK = 412
    PENCIL_CASE = 413
    SPORTS_EQUIPMENT = 414

    # TRANSPORTATION
    BICYCLE = 500
    SCOOTER = 501
    HELMET = 502


class Status(models.IntegerChoices):
    NEW = 100, "Submitted"  # automatically assigned whenever a report is created

    FLAGGED = 200, "Flagged"  # manually selected by a common user

    IN_PROGRESS = 300, "Under Review"  # automatically assigned whenever a site admin clicks on an item's detail report

    RESOLVED = 400, "Approved"  # manually selected by a site admin

    REJECTED = 500, "Rejected" # Manually selected by a site admin


def return_expiration_date():
    return (timezone.now() + timezone.timedelta(days=30)).date()


def date_validator(value):
    if timezone.now().date() < value:
        raise ValidationError(translate("The date an item was lost/found must not be in the future."))


class PhoneNumberValidator(RegexValidator):
    regex = r"(\+\d+ ?)?((\(\d{3}\))|(\d{3}))(-| )?(\d{3})(-| )?(\d{4})"
    message = "Phone number must include ten numeric digits, separated using spaces, dashes, or parentheses. Area code is optional."


class Item(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, default=None,
                             on_delete=models.SET_DEFAULT)

    item_name = models.CharField(max_length=50)
    description = models.TextField(max_length=500)

    location_category = models.ForeignKey(Location_Category, on_delete=models.CASCADE)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    status = models.PositiveIntegerField(choices=Status, default=100)
    tag = models.PositiveIntegerField(choices=Tag)

    date = models.DateField(validators=[date_validator], default=timezone.now)

    expiration_date = models.DateField(default=return_expiration_date)

    email = models.EmailField(blank=True, default=None, null=True)
    phone_number = models.CharField(max_length=50, blank=True, null=True, default=None,
                                    validators=[PhoneNumberValidator()])

    resolve_text = models.CharField(max_length=1024, blank=True, default=None, null=True)
    is_found = models.BooleanField(default=False)

    def __str__(self):
        return self.item_name


class ItemFile(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    file = models.FileField(upload_to='imageUpload/')
    type = models.CharField(max_length=30)


@receiver(post_delete, sender=ItemFile)
def delete_file_from_s3(sender, instance, **kwargs):
    if instance.file:
        file_path = instance.file.name
        if default_storage.exists(file_path):
            default_storage.delete(file_path)

items/forms.py
from django.forms import ModelForm, SelectDateWidget, FileField, ClearableFileInput, Textarea, ModelChoiceField
from django.utils.translation import gettext as translate
from django.utils import timezone
from django.core.exceptions import ValidationError
from django import forms
from .models import Item, Location, ItemFile, Location_Category, Tag


class MultipleFileInput(ClearableFileInput):
    allow_multiple_selected = True


class MultipleFileField(FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, file, initial=None):
        if isinstance(file, (list, tuple)):
            result = [super().clean(file, initial) for file in file]
        else:
            result = [super().clean(file, initial)]

        return result


def validate_file(file):
    max_size = 100000000  # ~ 100 MB
    valid_types = {
        'text/plain': ['txt'],
        'image/png': ['png'],
        'image/jpeg': ['jpeg', 'jpg'],
        'application/pdf': ['pdf'],
        # 'application/octet-stream': ['heic'],
    }

    filetype = file.content_type
    extension = file.__str__().split(".")[-1].strip().lower()

    if filetype in valid_types and extension in valid_types[filetype]:
        file.type = filetype.split('/')[-1].strip()
    else:
        raise ValidationError(translate("Please submit a valid file type."))

    if max_size and file.size > max_size:
        raise ValidationError(translate("File is too large."))


class ItemForm(ModelForm):
    files = MultipleFileField(required=False, widget=MultipleFileInput(attrs={'class': 'input-basic file'}))
    location_category = ModelChoiceField(queryset=Location_Category.objects.all())
    location = ModelChoiceField(queryset=Location.objects.all())

    class Meta:
        model = Item
        fields = ['item_name', 'description', 'location_category', 'location', 'date', 'email', 'phone_number', 'tag']
        widgets = {
            'date': SelectDateWidget(years=range(timezone.now().year - 5, timezone.now().year + 1),
                                     attrs={'class': 'input-basic narrow'}),
            'description': Textarea(attrs={'class': 'input-basic tall'}),
        }
        error_messages = {
            'item_name': {'required': 'Please enter the item name.'},
            'email': {'invalid': 'Please enter a valid email address.'},
        }
        exclude = ['user', 'is_found']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        self.is_found = kwargs.pop('is_found')
        super(ItemForm, self).__init__(*args, **kwargs)
        self.fields['location'].queryset = Location.objects.none()

        if 'location_category' in self.data:

            try:
                location_id = int(self.data.get('location_category'))
                self.fields['location'].queryset = Location.objects.filter(category__id = location_id).order_by("name")

            except (ValueError, TypeError):
                print(ValueError)

        elif self.instance.pk:
            self.fields['location'].queryset = self.instance.location_category.location_set.order_by('name')



        # Disable contact fields if the user is anonymous
        if not self.user.is_authenticated:
            self.user = None
            self.fields['email'].disabled = True
            self.fields['phone_number'].disabled = True

        # Update the location and tag blank choices
        self.fields['location_category'].empty_label = "Select..."
        self.fields['location'].empty_label = "Must select a location category."
        self.fields['tag'].choices = [("", "Select...")] + list(self.fields["tag"].choices)[1:]

        if not self.is_found:
            pass

        # Update input CSS classes
        for field in self.fields.values():
            if field.disabled is True:
                field.widget.attrs.update({'class': 'input-basic disabled'})
            elif field.widget.attrs.get('class', None) is None:
                field.widget.attrs.update({'class': 'input-basic'})

    def clean(self):
        cleaned_data = super().clean()

        if self.user is None:
            if cleaned_data['email'] is not None:
                self.add_error('email', translate("Sign in to share your email."))
            if cleaned_data['phone_number'] is not None:
                self.add_error('phone_number', translate("Sign in to share your phone number."))

        try:
            for file in cleaned_data['files']:
                validate_file(file)
        except ValidationError as error:
            self.add_error('files', error.message)

        if self.is_found:
            pass
            # location = cleaned_data['location']
            # if location.name == 'Other' and len(cleaned_data['files']) == 0:
            #     self.add_error('files', translate('File upload is required when location is OTHER.'))

        else:
            if self.user is None:
                self.add_error('__all__', translate('You must be signed in to submit this form.'))

    def save(self, commit=True):
        instance = super().save(commit=False)

        instance.user = self.user
        instance.is_found = self.is_found
        if commit:
            instance.save()

        for file in self.cleaned_data['files']:
            file_instance = ItemFile(item=instance, file=file, type=file.type)
            file_instance.save()

        return instance
    

class FilterForm(forms.Form):
        tag = forms.ChoiceField(choices=[], required=False)

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['tag'].choices = [("", "Select...")] + [
                (tag.value, tag.label) for tag in Tag
            ]

items/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden, JsonResponse
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.conf import settings
from django.utils import timezone
import json

from .forms import FilterForm, ItemForm
from .models import Item, Status, ItemFile, Location, Location_Category, Tag


class ReportItemView(generic.CreateView):
    form_class = ItemForm
    template_name = "items/report.html"
    success_url = reverse_lazy('items:report_success')
    is_found = None

    # Used to get the current user in ItemForm.__init__()
    def get_form_kwargs(self):
        kwargs = super(ReportItemView, self).get_form_kwargs()
        kwargs.update({'user': self.request.user, 'is_found': self.is_found})
        return kwargs

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated and not self.is_found:
            return HttpResponseRedirect(settings.LOGIN_URL)
        if request.user.is_authenticated and request.user.is_site_admin:
            return HttpResponseForbidden('As an admin, you are not allowed to make a report.')

        return super().dispatch(request, *args, **kwargs)

    def get_initial(self):
        initial = super().get_initial()

        if self.request.user.is_authenticated:
            initial['email'] = self.request.user.email

        return initial

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_found'] = self.is_found
        return context


class Index(LoginRequiredMixin, generic.ListView):
    template_name = "items/index.html"
    context_object_name = "items"
    is_found = None

    def get_queryset(self):
        today = timezone.now().date()
        tag = self.request.GET.get('tag')

        # Filter the queryset based on is_found
        items = Item.objects.filter(
            is_found=self.is_found,
            status__in=[Status.RESOLVED, Status.NEW, Status.IN_PROGRESS],
            expiration_date__gte=today  # This will only include items whose expiration date is today or later
        )
        # if a tag is specified, filter based on tag from already filtered list
        if tag:
            items = items.filter(tag=int(tag))
            
        # Order items by date
        items = items.order_by('-date')

        for item in items:
            item.files = list(ItemFile.objects.filter(item=item.id))

        return items

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_found'] = self.is_found
        context['tags'] = Tag.choices
        context['form'] = FilterForm(self.request.GET)
        return context


class Detail(LoginRequiredMixin, generic.DetailView):
    model = Item
    template_name = "items/details.html"
    context_object_name = "item"

    def dispatch(self, request, *args, **kwargs):
        item = self.get_object()
        if item.status != Status.RESOLVED and request.user != item.user and not request.user.is_site_admin:
            return HttpResponseForbidden("You are not allowed to view this item.")

        request.session['previous_url'] = request.META.get('HTTP_REFERER', None)
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        item = Item.objects.get(id=self.kwargs['id'])
        item.files = list(ItemFile.objects.filter(item=item.id))

        return item

    def get_context_data(self, **kwargs):
        context = super(Detail, self).get_context_data(**kwargs)
        context["can_flag"] = context['item'].status is not Status.FLAGGED or Status.IN_PROGRESS
        context['is_rejected'] = context['item'].status == Status.REJECTED
        context['location_name'] = self.get_location_name(context['item'].location_id)

        return context

    def get_location_name(self, location_id):
        location = get_object_or_404(Location, pk=location_id)
        return location.name


@login_required
def delete(request, id):
    item = get_object_or_404(Item, pk=id)

    # Check if the logged-in user is the owner of the item
    if not request.user.is_authenticated or item.user != request.user:
        return HttpResponseForbidden('You are not allowed to delete this post.')

    if request.method == 'POST':
        item.delete()
        messages.success(request, "Item deleted successfully.")

        previous_url = request.session.pop('previous_url', None)
        if previous_url:
            return HttpResponseRedirect(previous_url)
        return HttpResponseRedirect(reverse("index"))

    return HttpResponse(reverse("items:details", args=(id,)))


@login_required
def flag(request, id):
    item = get_object_or_404(Item, pk=id)

    if not request.user.is_authenticated:
        return HttpResponseForbidden('You are not allowed to flag this post.')

    if request.method == 'POST':
        if item.status == Status.RESOLVED or (item.status == Status.REJECTED and item.user == request.user):
            item.status = Status.FLAGGED
            item.save(update_fields=['status'])
            messages.success(request, "Item flagged successfully.")
        else:
            messages.warning(request, "This item cannot be flagged.")
            return HttpResponseRedirect(reverse('items:details', args=(id,)))

        previous_url = request.session.pop('previous_url', None)
        if previous_url:
            return HttpResponseRedirect(previous_url)
        return HttpResponseRedirect(reverse("index"))

    return HttpResponse(reverse('items:details', args=(id,)))


def getLocations(request):
    data = json.loads(request.body)

    location_categoryID = data["id"]

    possibleLocations = Location.objects.filter(category__id=location_categoryID)

    return JsonResponse(list(possibleLocations.values("id", "name")), safe=False)

templates/items/delete_modal.html
<!-- Bootstrap modal for logout confirmation -->
<div class="modal fade" id="deletePostModal" tabindex="-1" aria-labelledby="deletePostModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deletePostModalLabel">Confirm Post Deletion</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete your post?
            </div>
            <div class="modal-footer">
                <div class="submit-btn-container">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                </div>
                <form action="{% url 'items:delete' item.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Delete Post</button>
                </form>
            </div>
        </div>
    </div>
</div>

templates/items/details.html
<!DOCTYPE html>

{% extends "base.html" %}
{% load static %}

{% block content %}
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/item-detail.css' %}">
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <title>Item Detail</title>
    </head>

    <body>
    {% if user.is_authenticated %}
        <div class="content">
            <div class="detail-content-container">
                <div class="detail-info">
                    <div class="info-top-container">
                        <div class="header-tag-container">
                            <div class="header-container">
                                <div>
                                    <h3>{{ item }}</h3>
                                </div>
                            </div>
                        
                            {% if item.tag %}
                            <div class="tag-container">
                                <i class="fa fa-tag"></i>
                                <p class="tag-text">{{ item.get_tag_display }}</p>
                            </div>
                            {% endif %}
                        </div>

                        {% if item.location %}
                            <div class="specific-info-container" id="location-container">
                                <h4> Location: </h4>
                                <p> {{ location_name }} </p>
                            </div>
                        {% endif %}

                        {% if item.date %}
                            <div class="specific-info-container">
                                <h4>
                                Date 
                                {% if item.is_found %} Found: 
                                {% else %} Lost: {% endif %} 
                                </h4>
                                <p> {{ item.date }} </p>
                            </div>
                        {% endif %}

                        <div class="specific-info-container">
                            <h4> Contact information: </h4>
                            <p> 
                                {% if not item.email and not item.phone_number %}
                                    No contact information was provided.
                                {% endif %}
                                {% if item.email %}
                                    Email: {{ item.email }} <br>
                                {% endif %}
                                {% if item.phone_number %}
                                    Phone: {{ item.phone_number }}
                                {% endif %}
                            </p>
                        </div>

                        <div class="specific-info-container" id="description-container">
                            <h4>Description/Comments:</h4>
                            <div class="description-content">
                                {% if item.description %}
                                    <p>{{ item.description }}</p>
                                {% else %}
                                    <p>No comment was left</p>
                                {% endif %}
                            </div>
                        </div>
                    </div>

                    <hr/>

                    <div class="info-bottom-container">
                        <div class="status-container">
                            {% if user == item.user or user.is_site_admin %}
                                <div class="status-info">
                                    <h4>Post status:</h4>
                                    <p>{{ item.get_status_display }}</p>
                                </div>
                                {% if item.get_status_display == "Approved" or item.get_status_display == "Rejected" %}
                                    <div>
                                        {% include 'items/resolution_modal.html' %}
                                        <button id="resolutionMessageBtn" type="submit" class="btn btn-sm"
                                                data-bs-toggle="modal" data-bs-target="#resolutionModal">
                                            View Status Message
                                        </button>
                                    </div>
                                {% endif %}
                            {% endif %}
                        </div>

                        <div class="post-actions">
                            {% if can_flag and user != item.user %}
                                {% include 'items/flag_post_modal.html' %}
                                <div class="flag-post-container">
                                    <button style="padding-top: 0" id="flagBtn" type="submit" class="btn btn-sm" data-bs-toggle="modal"
                                            data-bs-target="#flagPostModal">
                                        <i class="fa fa-flag"></i> Flag
                                    </button>
                                    <flagtext> If this post contains concerning content, flag it for review.</flagtext>
                                </div>
                            {% elif user == item.user and is_rejected %}
                                <form method="post" action="{% url 'items:flag' item.id %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-sm"><i class="fa fa-flag"></i> Appeal Rejection</button>
                                </form>
                            {% endif %}

                            {% if user == item.user %}
                                <div class="delete-post-button-container">
                                    {% include 'items/delete_modal.html' %}
                                    <button id="deleteBtn" type="submit" class="btn btn-danger btn-sm"
                                            data-bs-toggle="modal" data-bs-target="#deletePostModal">
                                        <i class="fa fa-trash"></i> Delete
                                    </button>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>

                {% if item.files %}
                    <div class="files-container">
                        {% include 'items/carousel.html' %}
                    </div>
                {% endif %}
            </div>
        </div>
    {% else %}
        <p>
            As an anonymous user, you do not have access to this page. Please log in to view posts.
        </p>
    {% endif %}
    </body>
{% endblock %}

templates/items/index.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}

{% block content %}

    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" type="text/css" href="{% static 'css/item-detail.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>


    <body>
    <!-- Page title -->
    {% block title %}
        <div style="margin:auto; padding-top:2%">
            <h1>
                {% if is_found %}
                    Found
                {% else %}
                    Lost
                {% endif %}
                Items
            </h1>
        </div>
    {% endblock %}

    {% if user.is_authenticated %}
        <!-- form for filtering -->
        <div class="container p-3">
            <form method="get" action="{{ request.path }}" class="form-inline"
                  style="grid-column-start: 1; grid-column-end: 4">
                <div class="row align-items-center">
                    <div class="col-md-8">
                        <label for="id_tag" class="form-label">Select a tag:</label>
                        <select name="tag" id="id_tag" class="form-select">
                            {% for tag_value, tag_label in form.fields.tag.choices %}
                                <option value="{{ tag_value }}" {% if request.GET.tag == tag_value %}
                                        selected {% endif %}>
                                    {{ tag_label }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-md-4">
                        <br>
                        <input type="submit" value="Submit" class="btn btn-black">
                        <button type="submit" name="clear" class="btn btn-secondary">Clear Filters</button>
                    </div>
                </div>
            </form>
        </div>


        <div class="container p-3">
            {% if items %}
                {% for item in items %}
                    <div class="item-container" id="{{ item.id }}">
                        <div class="item-header">
                            <div class="item-name">
                                <h3 onclick="redirectToDetails('{{ item.id }}')">{{ item.item_name }}</h3>
                            </div>

                            {% if item.tag %}
                                <div class="tag-container">
                                    <i class="fa fa-tag"></i>
                                    <div class="tag-text">
                                        {{ item.get_tag_display }}
                                    </div>
                                </div>
                            {% endif %}
                        </div>

                        {% if item.files %}
                            <div class="files-container">
                                {% include 'items/carousel.html' %}
                            </div>
                        {% endif %}
                        <div class="item-details">
                            <div class="item-location">Location: {{ item.location }}</div>
                            <div class="item-date">
                                Date 
                                {% if item.is_found %} Found: 
                                {% else %} Lost: {% endif %} 
                                {{ item.date }}
                            </div>
                        </div>
                        <a href="{% url 'items:details' item.id %}" class="details-link">Click to view more details</a>
                    </div>
                {% endfor %}


            {% else %}
                {% block empty_message %}
                    <p> No items lost! </p>
                {% endblock %}
            {% endif %}
        </div>
    {% else %}
        <p> As an anonymous user, you do not have access to this page.
            Please log in to view posts. </p>
    {% endif %}
    <script>
        function redirectToDetails(itemId) {
            window.location.href = "{% url 'items:details' 0 %}".replace("0", itemId);
        }
    </script>
    </body>
{% endblock %}

templates/items/report_success.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block content %}

<head>
    <title>Item Reported Successfully!</title>
</head>

    <body>
    <div class="m-3" style="text-align:center">
        <p> Successfully submitted a report! </p>
        <a class="btn btn-black" href="{% url 'index' %}" role="button">Home</a>
    </div>

    <div class="m-3" style="text-align:center">
        <p> Submit another? </p>
        {% if user.is_authenticated %}
            <a class="btn btn-black" href="{% url 'items:report_lost' %}" role="button">Lost</a>
        {% endif %}
        <a class="btn btn-white" href="{% url 'items:report_found' %}" role="button">Found</a>
    </div>
    </body>
{% endblock %}

templates/items/resolution_modal.html
<!-- Modal -->
<div class="modal fade" id="resolutionModal" tabindex="-1" role="dialog" aria-labelledby="resolutionModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="resolutionModalLabel">Resolution Message</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                {% if item.resolve_text|length > 0 %}
                    <p>{{ item.resolve_text }}</p>
                {% else %}
                    <p>The admin did not leave a message for this post's resolution.</p>
                {% endif %}
                
            </div>
        </div>
    </div>
</div>